services:
  - type: web
    name: minha-loja-django
    env: python
    buildCommand: 
    
    ./post-deploy.sh 
    startCommand: "gunicorn loja.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: loja.settings
    staticPublishPath: staticfiles
